grails-app/domain/ib/storeroom/Perfume.groovy
package ib.storeroom

class Perfume {
  long externalId

  String name
  String brand

  int balance

  int volume
  double price

  static constraints = {
    externalId unique: true
    name blank: false
    brand blank: false
    balance min: 0
    volume min: 1
    price min: (0.01).toDouble()
  }
}

grails-app/controllers/storeroom/CatalogueController.groovy
package storeroom

import grails.plugin.springsecurity.annotation.Secured
import ib.storeroom.Perfume
import ib.storeroom.commands.EditPerfumeCommand
import ib.storeroom.commands.NewPerfumeCommand
import org.codehaus.groovy.runtime.InvokerHelper

class CatalogueController {
  def catalogueService

  @Secured(['ROLE_ADMIN', 'ROLE_READ_ONLY'])
  def index() {
    if (!params.offset) {
      params.offset = 0
    }

    if (!params.max) {
      params.max = grailsApplication.config.app.pagination
    }

    final searchString = params.search
    final searchLowBalance = params.searchLowBalance

    final pattern = "%$searchString%"
    final perfumes = Perfume.createCriteria().list(params) {
      and {
        if (searchString) {
          or {
            ilike("brand", pattern)
            ilike("name", pattern)
          }
        }

        if (searchLowBalance) {
          lt("balance", 5)
        }
      }
    }

    final perfumeCount = Perfume.createCriteria().count {
      and {
        if (searchString) {
          or {
            ilike("brand", pattern)
            ilike("name", pattern)
          }
        }

        if (searchLowBalance) {
          lt("balance", 5)
        }
      }
    }

    [
        perfumes        : perfumes,
        perfumeCount    : perfumeCount,
        search          : searchString,
        searchLowBalance: searchLowBalance
    ]
  }

  @Secured('ROLE_ADMIN')
  def create(NewPerfumeCommand command) {
    if (request.method == 'GET') {
      return render(view: "create")
    }

    final perfume = catalogueService.create(command)
    if (perfume.hasErrors()) {
      return render(view: "create", model: [perfume: perfume, errors: perfume.errors])
    }

    redirect(controller: "catalogue", action: "index")
  }

  @Secured('ROLE_ADMIN')
  def update(EditPerfumeCommand command) {
    final perfume = Perfume.get(command.id)

    if (request.method == 'GET') {
      return render(view: "update", model: [perfume: perfume])
    }

    final updatedPerfume = catalogueService.update(command)
    if (updatedPerfume.hasErrors()) {
      return render(view: "update", model: [perfume: perfume, errors: perfume.errors])
    }

    redirect(controller: "catalogue", action: "index")
  }

  @Secured('ROLE_ADMIN')
  def delete() {
    final id = params.id

    if (id) {
      catalogueService.delete(id)
    }

    redirect(controller: "catalogue", action: "index")
  }
}

grails-app/controllers/storeroom/ExportController.groovy
package storeroom

import grails.plugin.springsecurity.annotation.Secured
import ib.storeroom.Perfume
import ib.storeroom.commands.SearchPerfumeCommand
import ib.storeroom.fileexport.FileUtils
import ib.storeroom.fileexport.POIUtils
import org.apache.poi.hssf.usermodel.HSSFWorkbook
import org.apache.poi.ss.usermodel.CellStyle
import org.apache.poi.ss.usermodel.Font

class ExportController {
  def exportService

  @Secured(["ROLE_ADMIN", "ROLE_READ_ONLY"])
  def xls(SearchPerfumeCommand command) {
    final outputFile = new HSSFWorkbook();
    final sheet = outputFile.createSheet("Perfumes")

    sheet.createRow(0).with {
      CellStyle style = outputFile.createCellStyle();
      Font font = outputFile.createFont();
      font.setBold(true);
      style.setFont(font);

      ["SKU", "Name", "Brand", "Volume", "Price", "Balance"].eachWithIndex { String colHeader, int column ->
        createCell(column).with {
          setCellStyle(style)
          setCellValue(colHeader)
        }
      }
    }

    exportService.values(command).eachWithIndex { Perfume perfume, int index ->
      use(POIUtils) {
        perfume.toRow(sheet.createRow(index + 1))
      }
    }

    response.contentType = 'application/vnd.ms-excel'
    response.addHeader("Content-Disposition", "attachment;filename=${FileUtils.generateFileName(command)}.xls")

    outputFile.write(response.outputStream)
    outputFile.close()

    response.outputStream.flush()
  }
}

grails-app/controllers/storeroom/ImportController.groovy
package storeroom

import grails.plugin.springsecurity.annotation.Secured
import ib.storeroom.fileimport.ImportFileParser

@Secured('ROLE_ADMIN')
class ImportController {
  def importService

  def index() {
  }

  def upload() {
    final receptionFile = request.getFile('reception')

    if (!receptionFile.isEmpty()) {
      final filename = receptionFile.filename
      final extension = filename.drop(filename.lastIndexOf('.') + 1)

      final parser = ImportFileParser.REGISTRY[extension]
      if (!parser) {
        return render(view: "upload", model: [fileName: filename, error: "Unsupported file extension: ${extension}"])
      }

      try {
        final rawEntries = parser.parse(receptionFile)
        final importResult = importService.processEntries(rawEntries)
        render(view: "upload", model: [fileName: filename, result: importResult])
      } catch (e) {
        render(view: "upload", model: [fileName: filename, error: e.message])
      }
    } else {
      render(view: "index")
    }
  }
}

grails-app/controllers/storeroom/UrlMappings.groovy
package storeroom

class UrlMappings {

  static mappings = {
    "/$controller/$action?/$id?(.$format)?" {
      constraints {
        // apply constraints here
      }
    }

    "/"(redirect: "/catalogue")
    "500"(view: '/error')
    "404"(view: '/notFound')
  }
}

grails-app/controllers/storeroom/UserController.groovy
package storeroom

import grails.plugin.springsecurity.annotation.Secured
import ib.storeroom.auth.Role
import ib.storeroom.auth.User
import ib.storeroom.commands.DeleteUserCommand
import ib.storeroom.commands.NewUserCommand
import ib.storeroom.commands.UserDetailsCommand

@Secured('ROLE_ADMIN')
class UserController {
  def userService

  def index() {
    [users: User.list()]
  }

  def create(NewUserCommand command) {
    if (request.method == 'GET') {
      return render(view: 'create')
    }

    final user = userService.create(command)
    if (user.hasErrors()) {
      return render(view: 'create', model: [user: user, errors: user.errors])
    }

    redirect(contoller: 'user', action: 'index')
  }

  def update(UserDetailsCommand command) {
    if (request.method == 'GET') {
      final user = User.get(command.id)
      return render(view: 'update', model: [user: user])
    }

    userService.update(command)
    redirect(contoller: 'user', action: 'index')
  }

  def delete(DeleteUserCommand command) {
    userService.delete(command)
    redirect(contoller: 'user', action: 'index')
  }
}

grails-app/views/catalogue/_perfume.gsp
<div class="form-group">
  <label class="col-md-4 control-label">Name</label>

  <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
      <input name="name" placeholder="Name" class="form-control" type="text" value="${perfume ? perfume.name : ''}">
      <span class="input-group-addon"></span>
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label">Brand</label>

  <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
      <input name="brand" placeholder="Brand" class="form-control" type="text" value="${perfume ? perfume.brand : ''}">
      <span class="input-group-addon"></span>
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label">Volume</label>

  <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
      <input name="volume" placeholder="Volume" class="form-control" type="text"
             value="${perfume ? perfume.volume : ''}">
      <span class="input-group-addon">mL</span>
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label">Price</label>

  <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
      <input name="price" placeholder="Price" class="form-control" type="text" value="${perfume ? perfume.price : ''}">
      <span class="input-group-addon">$</span>
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label">Balance</label>

  <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
      <input name="balance" placeholder="Balance" class="form-control" type="text" value="${perfume ? perfume.balance : ''}">
      <span class="input-group-addon"></span>
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label">External ID</label>

  <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
      <input name="externalId" placeholder="SKU" class="form-control" type="text"
             value="${perfume ? perfume.externalId : ''}">
      <span class="input-group-addon"></span>
    </div>
  </div>
</div>

grails-app/views/catalogue/create.gsp
<!doctype html>
<html>
<head>
  <meta name="layout" content="main"/>
  <title>Perfume Storeroom</title>
</head>

<body>
<div class="container">
  <g:form action="create" method="post" controller="catalogue" class="well form-horizontal">
    <g:if test="${errors}">
      <h3 class="text-danger">Please fill all fields correctly</h3>
    </g:if>

    <br>

    <legend>New perfume</legend>
    <fieldset>
      <g:render template="perfume" model="${[perfume: perfume]}"/>

      <div class="form-group">
        <label class="col-md-4 control-label"></label>

        <div class="col-md-4">
          <button type="submit" class="btn btn-success">Create</button>
        </div>
      </div>

    </fieldset>
  </g:form>
</div>
</body>

grails-app/views/catalogue/index.gsp
<!doctype html>
<html>
<head>
  <meta name="layout" content="main"/>
  <title>Perfume Storeroom</title>
</head>

<body>

<br>
<g:form controller="catalogue" action="index">
  <div class="input-group">
    <span class="input-group-addon glyphicon glyphicon-search" id="basic-addon1"></span>
    <input type="text" class="form-control" placeholder="Search..." aria-describedby="basic-addon1"
           value="${search}" name="search">
    <span class="input-group-addon">
      <g:checkBox name="searchLowBalance" aria-label="less than 5 items in warehouse" value="${searchLowBalance}"
                  onChange="this.form.submit()"/> only low balance</span>
  </div>
</g:form>

<div class="row" style="padding: 20px 0 20px 0">
  <div class="col-md-2" style="float: left"><a href="${createLink(controller: "catalogue", action: "create")}"
                                               class="btn btn-success">New perfume</a></div>

  <div class="col-md-2 col-md-offset-8">
    <div class="dropdown">
      <button class="btn btn-info dropdown-toggle" type="button" id="exportMenu" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="true">
        Export table
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" aria-labelledby="exportMenu">
        <li><g:link controller="export" action="xls"
                    params="${[search: search, searchLowBalance: searchLowBalance]}">Excel (*.xls)</g:link></li>
      </ul>
    </div>
  </div>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <g:sortableColumn property="externalId" title="SKU"/>
    <g:sortableColumn property="name" title="Name"/>
    <g:sortableColumn property="brand" title="Brand"/>
    <g:sortableColumn property="balance" title="Balance"/>
    <g:sortableColumn property="volume" title="Volume"/>
    <g:sortableColumn property="price" title="Price"/>
    <th></th>
  </tr>
  </thead>

  <tbody>

  <g:each var="perfume" in="${perfumes}">
    <tr>
      <td>${perfume.externalId}</td>
      <td>${perfume.name}</td>
      <td>${perfume.brand}</td>
      <td>${perfume.balance}</td>
      <td>${perfume.volume}</td>
      <td>${perfume.price}</td>
      <td>
        <a href="${createLink(controller: "catalogue", action: "update", params: [id: perfume.id])}"
           class="btn btn-default perfume-action" aria-label="Left Align">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        </a>

        <g:form controller="catalogue" action="delete">
          <input type="hidden" name="id" value="${perfume.id}"/>
          <button type="submit" class="btn btn-danger perfume-action" aria-label="Left Align">
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          </button>
        </g:form>
      </td>
    </tr>
  </g:each>
  </tbody>

  <tfoot>
  <tr>
    <td colspan="6">
      <b><g:if test="${search}">Search results</g:if> <g:else>Total</g:else></b>: ${perfumeCount}
    </td>

  </tr>
  </tfoot>
</table>

<div class="perfume-pagination">
  <g:paginate next="Forward" prev="Back" maxsteps="0"
              max="${grailsApplication.config.app.pagination}" controller="catalogue" action="index"
              total="${perfumeCount}" params="${[search: search]}"/>
</div>
</body>
</html>

grails-app/views/catalogue/update.gsp
<!doctype html>
<html>
<head>
  <meta name="layout" content="main"/>
  <title>Perfume Storeroom</title>
</head>

<body>
<div class="container">
  <g:form controller="catalogue" class="well form-horizontal" action="update" method="post">
    <g:hiddenField name="id" value="${perfume.id}"/>

    <g:if test="${errors}">
      <h3 class="text-danger">Please fill all fields correctly</h3>
    </g:if>

    <br>
    <legend>Edit perfume</legend>
    <fieldset>
      <g:render template="perfume" model="${[perfume: perfume]}"/>

      <div class="form-group">
        <label class="col-md-4 control-label"></label>

        <div class="col-md-4">
          <button type="submit" class="btn btn-default">Update</button>
        </div>
      </div>

    </fieldset>
  </g:form>
</div>
</body>

grails-app/views/import/index.gsp
<!doctype html>
<html>
<head>
  <meta name="layout" content="main"/>
  <title>Perfume Storeroom</title>

</head>

<body>

<g:javascript>
  $(document).on('click', '.browse', function () {
    var file = $(this).parent().parent().parent().find('.file');
    file.trigger('click');
  });

  $(document).on('change', '.file', function () {
    $(this).parent().find('.form-control').val($(this).val());
  });
</g:javascript>


<div class="container">
  <g:uploadForm action="upload" style="display: inline">
    <h3>Select file to import</h3>
    <br>

    <div class="form-group">
      <input type="file" name="reception" class="file">

      <div class="input-group col-xs-12">
        <span class="input-group-addon"><i class="glyphicon glyphicon-file"></i></span>

        <input type="text" class="form-control input-lg" disabled
               placeholder="Select file with perfumes (*.xls, *.csv)">

        <span class="input-group-btn">
          <button class="browse btn btn-primary input-lg" type="button"><i
              class="glyphicon glyphicon-search"></i> Browse</button>
        </span>

        <span></span>

        <span class="input-group-btn">
          <input type="submit" class="btn btn-success input-lg" value="Upload"/>
        </span>
      </div>
    </div>
  </g:uploadForm>

</div>
</body>
</html>

grails-app/views/import/upload.gsp
<!doctype html>
<html>
<head>
  <meta name="layout" content="main"/>
  <title>Perfume Storeroom</title>
</head>

<body>

<div class="container">
  <g:if test="${error}">
    <h3 class="text-danger">Error while processing <b>${fileName}</b></h3>
    <br>
    <h4 class="text-danger">${error}</h4>
  </g:if>
  <g:else>
    <h3 class="text-info">File <b>${fileName}</b> processed</h3>

    <br>
    <h4>Rows
      <span class="text-success">imported: ${result.imported}</span> / <span
        class="text-danger">skipped: ${result.skipped}</span>
    </h4>
    <br>

    <g:if test="${result.notes}">
      <table class="table table-striped">
        <thead>
        <tr>
          <td colspan="3" style="width: 50%"><h4>Entry</h4></td>
          <td rowspan="2"><h4>Error</h4></td>
        </tr>
        <tr>
          <td>SKU</td>
          <td>Name</td>
          <td>Balance</td>
          <td></td>
        </tr>
        </thead>
        <tbody>
        <g:each var="note" in="${result.notes}">
          <tr class="${note.type}">
            <td>${note.entry.sku}</td>
            <td>${note.entry.name}</td>
            <td>${note.entry.balance}</td>
            <td class="text-${note.type.toString().toLowerCase()}">${note.message}</td>
          </tr>
        </g:each>
        </tbody>
      </table>
    </g:if>
  </g:else>
</div>
</body>
</html>

grails-app/views/layouts/main.gsp
<!doctype html>
<html>
<head>
  <title>
    <g:layoutTitle default="Perfume Storeroom"/>
  </title>

  <asset:stylesheet src="application.css"/>

  <g:layoutHead/>

  <asset:javascript src="application.js"/>

  <link rel="icon" type="image/png" href="${resource(dir: 'images', file: 'perfume.png')}" />
</head>

<body>
<div class="container">
  <div class="header clearfix">
    <nav>
      <ul class="nav nav-pills pull-right">
        <g:menuItem controller="catalogue" action="index">Catalogue</g:menuItem>
        <g:menuItem controller="import" action="index">Import</g:menuItem>
        <g:menuItem controller="user" action="index">Users</g:menuItem>
      </ul>
    </nav>

    <h3 class="text-muted"><img src="${resource(dir: 'images', file: 'perfume.png')}" alt="Logo"
                                border="0"/> Perfume Storeroom
    </h3>
  </div>

  <g:layoutBody/>

  <div class="footer">
  Whats up <i class="glyphicon glyphicon-user"></i> <sec:loggedInUserInfo field="username"/>? (<a href="/logoff">run away</a>)
  </div>
</div>
</body>
</html>

grails-app/views/user/_userForm.gsp
<div class="form-group">
  <label class="col-md-4 control-label">Username</label>

  <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
      <input name="username" placeholder="Name" class="form-control" type="text" value="${user ? user.username : ''}">
      <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label">Password</label>

  <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
      <input id="password" type="password" class="form-control" name="password" placeholder="Password">
      <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label">Read only</label>

  <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
      <input id="readOnly" type="checkbox" class="form-control" name="readOnly">
    </div>
  </div>
</div>

grails-app/views/user/create.gsp
<!doctype html>
<html>
<head>
  <meta name="layout" content="main"/>
  <title>Perfume Storeroom - New user</title>
</head>

<body>
<div class="container">
  <br>

  <g:form action="create" method="post" controller="user" class="well form-horizontal">
    <g:if test="${errors}">
      <h3 class="text-danger">Please fill all fields correctly</h3>
    </g:if>

    <br>

    <legend>New user</legend>
    <fieldset>
      <g:render template="userForm" model="${[user: user]}"/>

      <div class="form-group">
        <label class="col-md-4 control-label"></label>

        <div class="col-md-4">
          <button type="submit" class="btn btn-success">Create</button>
        </div>
      </div>
    </fieldset>
  </g:form>
</div>
</body>

grails-app/views/user/index.gsp
<!doctype html>
<html>
<head>
  <meta name="layout" content="main"/>
  <title>Perfume Storeroom - Users</title>
</head>

<body>

<br>

<div class="row" style="padding: 0 0 20px 0">
  <div class="col-md-2" style="float: left"><a href="${createLink(controller: "user", action: "create")}"
                                               class="btn btn-success">New user</a></div>
</div>

<table class="table table-striped" id="usersTable">
  <thead>
  <tr>
    <th>Username</th>
    <th>Administrator</th>
    <th>Read only</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <g:each in="${users}" var="user">
    <g:set var="readOnly" value="${user.roles.find { it.name == 'ROLE_READ_ONLY' }}"/>
    <tr>
      <td>${user.username}</td>
      <td><g:if test="${!readOnly}"><img src="${resource(dir: 'images', file: 'checked_user.png')}"/></g:if></td>
      <td><g:if test="${readOnly}"><img src="${resource(dir: 'images', file: 'checked_user.png')}"/></g:if></td>
      <td>
        <a href="${createLink(controller: "user", action: "update", params: [id: user.id])}"
           class="btn btn-default perfume-action" aria-label="Left Align">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        </a>

        <g:form controller="user" action="delete">
          <input type="hidden" name="id" value="${user.id}"/>
          <button type="submit" class="btn btn-danger perfume-action" aria-label="Left Align">
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          </button>
        </g:form>
      </td>
    </tr>
  </g:each>
  </tbody>
</table>
</body>
</html>

grails-app/views/user/update.gsp
<!doctype html>
<html>
<head>
  <meta name="layout" content="main"/>
  <title>Perfume Storeroom</title>
</head>

<body>
<div class="container">
  <g:form controller="user" class="well form-horizontal" action="update" method="post">
    <g:hiddenField name="id" value="${user.id}"/>

    <g:if test="${errors}">
      <h3 class="text-danger">Please fill all fields correctly</h3>
    </g:if>

    <br>
    <legend>Edit user</legend>
    <fieldset>
      <g:render template="userForm" model="${[user: user]}"/>

      <div class="form-group">
        <label class="col-md-4 control-label"></label>

        <div class="col-md-4">
          <button type="submit" class="btn btn-default">Update</button>
        </div>
      </div>

    </fieldset>
  </g:form>
</div>
</body>